def format_report(raw_content):
    """
    Format the raw content into a structured report.
    
    Args:
    - raw_content (str): The raw content (text report) generated by the AI.
    
    Returns:
    - str: The formatted report ready to be displayed in Streamlit.
    """
    report = f"""
    ## AI Learning Report 📘

    {raw_content}

    ---
    *Generated by Gemini AI*
    """
    
    return report
